language: cpp
compiler: gcc

install: 
  # cppcheck
  - sudo apt-get install -qq cppcheck

script: 
  # Build and run this project
  - qmake
  - make
  - ./cppcheck
  # cppcheck (mild)
  - cppcheck --quiet . 
  # cppcheck that makes the Travis build fail
  #- cppcheck --quiet --error-exitcode=1 . 
